In [2]:
import random
random.random()

0.1246233240304383

构建一些没有播种的随机数据。该random.random()函数返回区间 [0.0, 1.0) 中的随机浮点数。结果将始终小于右侧端点 (1.0)。这也称为半开放范围：

In [3]:
random.random()

0.12819348030406186

使用random.seed()，您可以使结果可重现，之后的调用链random.seed()将产生相同的数据轨迹：

In [8]:
random.seed(333)
random.random()


0.5548354562432166

In [9]:
random.seed(333)
random.random()

0.5548354562432166

random.randint()函数在 Python 中的两个端点之间生成一个随机整数.这跨越了完整的 [x, y] 区间并且可能包括两个端点：

In [10]:
random.randint(0,10)

5

In [11]:
random.randint(500,5000)

2267

使用random.randrange()，您可以排除区间的右侧，这意味着生成的数字始终位于 [x, y) 内，并且始终小于右端点

In [12]:
random.randrange(0,10)

6

In [13]:
random.randrange(0,10)

1

如果您需要生成位于特定 [x, y] 区间内的随机浮点数，您可以使用random.uniform()，它从连续均匀分布中提取：

In [18]:
random.uniform(20,30)

24.197030011725477

In [21]:
items = ['apple','banana','orange','grape']
random.choice(items)

'banana'

In [22]:
random.choice(items)

'grape'

In [36]:
random.choices(items,k = 2)

['grape', 'grape']

In [35]:
random.choices(items,k = 3)

['grape', 'apple', 'apple']

In [37]:
random.sample(items,3) #不重样


['orange', 'banana', 'grape']

In [41]:
random.shuffle(items)  #随机排列
items

['apple', 'grape', 'banana', 'orange']

In [45]:
[random.random() for _ in range(5)]

[0.24505988628667785,
 0.2068398283884113,
 0.19267218331187486,
 0.5618099084051984,
 0.2976771614146929]

# numpy部分

In [51]:
import numpy as np
np.random.seed(555)
np.set_printoptions(precision = 3)

In [57]:
np.random.rand(4)

array([0.515, 0.355, 0.968, 0.75 ])

In [53]:
np.random.randn(3,4)

array([[-0.157,  0.437, -0.846,  2.167],
       [ 0.334, -0.378,  0.596,  2.053],
       [-0.04 , -0.577, -0.061,  0.998]])

In [55]:
np.random.choice([0,1],p = [0.7,0.3],size = (5,5))

array([[0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0]])

In [56]:
5 * np.random.random_sample((3,2)) - 5

array([[-2.951, -4.711],
       [-2.288, -0.766],
       [-0.876, -3.796]])

In [ ]:
items = ['apple','banana','orange','grape']

In [63]:
np.random.shuffle(items)
items

['banana', 'apple', 'orange', 'grape']